# Generated by Django 4.2.5 on 2023-09-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurshipManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partners', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=600)),
                ('applications', models.CharField(blank=True, max_length=900, null=True)),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='entrepreneurship_management/')),
            ],
            options={
                'verbose_name': 'entrepreneurship management',
                'db_table': 'entrepreneurship_management',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('description', models.TextField(max_length=1500)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partners', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offices/')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
                'db_table': 'office',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WelfareApprentice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1500)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partners', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=100)),
                ('aditional_info_current', models.CharField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='welfare_apprentice/')),
            ],
            options={
                'verbose_name': 'welfare apprentice',
                'db_table': 'welfare_apprentice',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('description', models.TextField(max_length=1500)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partners', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_offices/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_offices', to='office.office')),
            ],
            options={
                'verbose_name': 'sub office',
                'verbose_name_plural': 'sub offices',
                'db_table': 'sub_office',
                'ordering': ['name'],
            },
        ),
    ]
