# Generated by Django 4.2.5 on 2023-09-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurshipmanagement',
            name='applications',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurshipmanagement',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurshipmanagement',
            name='partners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='partners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='suboffice',
            name='partners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='welfareapprentice',
            name='aditional_info_current',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='welfareapprentice',
            name='partners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
