# Generated by Django 4.2.5 on 2023-09-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(max_length=1000)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'formation area',
                'verbose_name_plural': 'formation areas',
                'db_table': 'formation_area',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('technical', 'Technical'), ('technologist', 'Technologist'), ('operator', 'Operator'), ('specialization', 'Specialization'), ('assistant', 'Assistant')], default='technical', max_length=15, unique=True)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_types', to='formation_area.formationarea')),
            ],
            options={
                'verbose_name': 'program type',
                'verbose_name_plural': 'program types',
                'db_table': 'program_type',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(max_length=1000)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=10)),
                ('formation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation_area.formationarea')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='formation_area.programtype')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'db_table': 'program',
                'ordering': ['name'],
            },
        ),
    ]
