# Generated by Django 4.2.5 on 2023-09-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formation_areas/'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formation_areas/'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='type',
            field=models.CharField(choices=[('technical', 'Technical'), ('technologist', 'Technologist'), ('operator', 'Operator'), ('specialization', 'Specialization'), ('assistant', 'Assistant')], default='technical', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='programtype',
            constraint=models.UniqueConstraint(fields=('formation_area', 'type'), name='unique_program_type'),
        ),
    ]
